LineLength:
  Enabled: false

MethodLength:
  Max: 30

SymbolName:
  AllowCamelCase: false

Documentation:
  Enabled: false

AllCops:
    Includes:
        - Gemfile
    Excludes:
        - report/config.rb
