# Default Chemisty Kit Configuration File

base_url: http://google.com
concurrency: 1
screenshot_on_fail:
selenium_connect:
    log: 'evidence'
    host: 'localhost'
basic_auth:
    username: 'user'
    password: 'pass'
    http_path: '/basic'
    https_path: '/secure'
split_testing:
    provider: 'optimizely'
    opt_out: true
