# Default Chemisty Kit Configuration File

base_url: http://google.com
concurrency: 1
screenshot_on_fail:
log:
    path: 'evidence'
    results_file: 'results_junit.xml'
    format: 'junit'
selenium_connect:
    log: 'evidence'
    host: 'localhost'
